# Site settings
name: Muhammad A. Jarral
email: ahsan.jarral@gmail.com
#canonical_url: https://example.com
keywords: "Software Engineer, PHP, Web Developer, Machine Learning, Deep Learning, Startups, Agile, Pair Programming"
skills: "Software Engineer in Derby, UK"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/ahsanjarral
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
